
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VPaned vpaned1;

	private global::Gtk.HBox hbox1;

	private global::Gtk.VBox vbox3;

	private global::Gtk.Label label5;

	private global::Gtk.RadioButton darkAI;

	private global::Gtk.RadioButton lightAI;

	private global::Gtk.HBox hbox7;

	private global::Gtk.Label label7;

	private global::Gtk.Label timeLabel;

	private global::Gtk.VBox vbox1;

	private global::Gtk.Label label1;

	private global::Gtk.ScrolledWindow historyBox;

	private global::Gtk.TextView logBox;

	private global::Gtk.HBox hbox2;

	private global::Gtk.Fixed boardPanel;

	private global::Gtk.Image boardImage;

	private global::Gtk.VButtonBox vbuttonbox4;

	private global::Gtk.Button restartButton;

	private global::Gtk.Button playButton;

	private global::Gtk.Button stopButton;

	private global::Gtk.Button undoButton;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Cannon");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(3));
		this.DefaultWidth = 1000;
		this.DefaultHeight = 1000;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vpaned1 = new global::Gtk.VPaned();
		this.vpaned1.CanFocus = true;
		this.vpaned1.Name = "vpaned1";
		this.vpaned1.Position = 149;
		// Container child vpaned1.Gtk.Paned+PanedChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox3 = new global::Gtk.VBox();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.label5 = new global::Gtk.Label();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("AI Player:");
		this.vbox3.Add(this.label5);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.label5]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.darkAI = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("DARK Player"));
		this.darkAI.CanFocus = true;
		this.darkAI.Name = "darkAI";
		this.darkAI.DrawIndicator = true;
		this.darkAI.UseUnderline = true;
		this.darkAI.Group = new global::GLib.SList(global::System.IntPtr.Zero);
		this.vbox3.Add(this.darkAI);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.darkAI]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.lightAI = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("LIGHT Player"));
		this.lightAI.CanFocus = true;
		this.lightAI.Name = "lightAI";
		this.lightAI.DrawIndicator = true;
		this.lightAI.UseUnderline = true;
		this.lightAI.Group = this.darkAI.Group;
		this.vbox3.Add(this.lightAI);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.lightAI]));
		w3.Position = 2;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox7 = new global::Gtk.HBox();
		this.hbox7.Name = "hbox7";
		this.hbox7.Spacing = 6;
		// Container child hbox7.Gtk.Box+BoxChild
		this.label7 = new global::Gtk.Label();
		this.label7.Name = "label7";
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("AI Timer:");
		this.hbox7.Add(this.label7);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.label7]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbox7.Gtk.Box+BoxChild
		this.timeLabel = new global::Gtk.Label();
		this.timeLabel.Name = "timeLabel";
		this.timeLabel.LabelProp = global::Mono.Unix.Catalog.GetString("00:00");
		this.hbox7.Add(this.timeLabel);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.timeLabel]));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		this.vbox3.Add(this.hbox7);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox7]));
		w6.Position = 3;
		w6.Expand = false;
		w6.Fill = false;
		this.hbox1.Add(this.vbox3);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox3]));
		w7.Position = 0;
		w7.Expand = false;
		w7.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Move history");
		this.vbox1.Add(this.label1);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.label1]));
		w8.Position = 0;
		w8.Expand = false;
		w8.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.historyBox = new global::Gtk.ScrolledWindow();
		this.historyBox.WidthRequest = 750;
		this.historyBox.Name = "historyBox";
		this.historyBox.VscrollbarPolicy = ((global::Gtk.PolicyType)(0));
		this.historyBox.ShadowType = ((global::Gtk.ShadowType)(1));
		this.historyBox.BorderWidth = ((uint)(3));
		// Container child historyBox.Gtk.Container+ContainerChild
		this.logBox = new global::Gtk.TextView();
		this.logBox.Buffer.Text = global::Mono.Unix.Catalog.GetString("--- TOP ---\n");
		this.logBox.CanFocus = true;
		this.logBox.Name = "logBox";
		this.logBox.Editable = false;
		this.historyBox.Add(this.logBox);
		this.vbox1.Add(this.historyBox);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.historyBox]));
		w10.Position = 1;
		this.hbox1.Add(this.vbox1);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox1]));
		w11.Position = 1;
		w11.Expand = false;
		w11.Fill = false;
		this.vpaned1.Add(this.hbox1);
		global::Gtk.Paned.PanedChild w12 = ((global::Gtk.Paned.PanedChild)(this.vpaned1[this.hbox1]));
		w12.Resize = false;
		// Container child vpaned1.Gtk.Paned+PanedChild
		this.hbox2 = new global::Gtk.HBox();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.boardPanel = new global::Gtk.Fixed();
		this.boardPanel.Name = "boardPanel";
		this.boardPanel.HasWindow = false;
		// Container child boardPanel.Gtk.Fixed+FixedChild
		this.boardImage = new global::Gtk.Image();
		this.boardImage.Name = "boardImage";
		this.boardImage.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Cannon_GUI.board.svg");
		this.boardPanel.Add(this.boardImage);
		this.hbox2.Add(this.boardPanel);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.boardPanel]));
		w14.Position = 0;
		w14.Expand = false;
		w14.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.vbuttonbox4 = new global::Gtk.VButtonBox();
		this.vbuttonbox4.Name = "vbuttonbox4";
		this.vbuttonbox4.Spacing = 10;
		this.vbuttonbox4.BorderWidth = ((uint)(10));
		this.vbuttonbox4.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(3));
		// Container child vbuttonbox4.Gtk.ButtonBox+ButtonBoxChild
		this.restartButton = new global::Gtk.Button();
		this.restartButton.CanFocus = true;
		this.restartButton.Name = "restartButton";
		this.restartButton.UseUnderline = true;
		this.restartButton.Label = global::Mono.Unix.Catalog.GetString("Restart");
		global::Gtk.Image w15 = new global::Gtk.Image();
		w15.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-refresh", global::Gtk.IconSize.Button);
		this.restartButton.Image = w15;
		this.vbuttonbox4.Add(this.restartButton);
		global::Gtk.ButtonBox.ButtonBoxChild w16 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox4[this.restartButton]));
		w16.Expand = false;
		w16.Fill = false;
		// Container child vbuttonbox4.Gtk.ButtonBox+ButtonBoxChild
		this.playButton = new global::Gtk.Button();
		this.playButton.CanFocus = true;
		this.playButton.Name = "playButton";
		this.playButton.UseUnderline = true;
		this.playButton.Label = global::Mono.Unix.Catalog.GetString("Play");
		global::Gtk.Image w17 = new global::Gtk.Image();
		w17.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-media-play", global::Gtk.IconSize.Menu);
		this.playButton.Image = w17;
		this.vbuttonbox4.Add(this.playButton);
		global::Gtk.ButtonBox.ButtonBoxChild w18 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox4[this.playButton]));
		w18.Position = 1;
		w18.Expand = false;
		w18.Fill = false;
		// Container child vbuttonbox4.Gtk.ButtonBox+ButtonBoxChild
		this.stopButton = new global::Gtk.Button();
		this.stopButton.CanFocus = true;
		this.stopButton.Name = "stopButton";
		this.stopButton.UseUnderline = true;
		this.stopButton.Label = global::Mono.Unix.Catalog.GetString("Stop");
		global::Gtk.Image w19 = new global::Gtk.Image();
		w19.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-media-stop", global::Gtk.IconSize.Menu);
		this.stopButton.Image = w19;
		this.vbuttonbox4.Add(this.stopButton);
		global::Gtk.ButtonBox.ButtonBoxChild w20 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox4[this.stopButton]));
		w20.Position = 2;
		w20.Expand = false;
		w20.Fill = false;
		// Container child vbuttonbox4.Gtk.ButtonBox+ButtonBoxChild
		this.undoButton = new global::Gtk.Button();
		this.undoButton.CanFocus = true;
		this.undoButton.Name = "undoButton";
		this.undoButton.UseUnderline = true;
		this.undoButton.Label = global::Mono.Unix.Catalog.GetString("Undo");
		global::Gtk.Image w21 = new global::Gtk.Image();
		w21.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-undo", global::Gtk.IconSize.Menu);
		this.undoButton.Image = w21;
		this.vbuttonbox4.Add(this.undoButton);
		global::Gtk.ButtonBox.ButtonBoxChild w22 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox4[this.undoButton]));
		w22.Position = 3;
		w22.Expand = false;
		w22.Fill = false;
		this.hbox2.Add(this.vbuttonbox4);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.vbuttonbox4]));
		w23.Position = 1;
		w23.Expand = false;
		w23.Fill = false;
		this.vpaned1.Add(this.hbox2);
		this.Add(this.vpaned1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.darkAI.Toggled += new global::System.EventHandler(this.ChangeAI);
		this.lightAI.Toggled += new global::System.EventHandler(this.ChangeAI);
		this.restartButton.Clicked += new global::System.EventHandler(this.Reset);
	}
}
